# Generated by Django 4.2 on 2023-04-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectmodel',
            name='team',
            field=models.CharField(default='Australia', max_length=20),
        ),
    ]
